Hard constraints for type check
cmudig/draco2 pull request #205
Opened 2022-02-08 18:11 UTC by Zehua-Zeng

Hard constraints from Draco1 hard.lp "type check" section.

2022-02-08 18:31 UTC, domoritz commented
Please update the title of the pull request according to https://www.conventionalcommits.org/en/v1.0.0/

2022-02-08 19:26 UTC, Zehua-Zeng commented
> Please update the title of the pull request according to https://www.conventionalcommits.org/en/v1.0.0/. Also make sure that tests pass locally.

Done.

2022-02-08 22:53 UTC, domoritz requested changes
Do we still need these checks with https://github.com/cmudig/draco2/blob/0beb90705bbe6108e143c703b9c4c3db7df74f4b/draco/asp/constraints.lp#L4? I suspect that many checks are redundant now. Try removing them but leave the tests and see whether they start failing.

2022-02-09 00:04 UTC, domoritz requested changes

2022-02-09 00:04 UTC, domoritz commented on draco/asp/hard.lp
> +% ====== Hard constraints ======
Why has this changed?

2022-02-09 00:04 UTC, domoritz commented on draco/asp/helpers.lp
> +% ====== Helpers ======
Something changed about the whitespaced here. Please undo.

2022-02-15 20:49 UTC, closed without merging

2022-02-15 22:22 UTC, domoritz commented
You don't need to reopen a new pull request. You can usually push code to the branch for a pull request.

2022-02-18 17:11 UTC, Zehua-Zeng commented
I tried to merge the new version but did something wrong, and messed up the code, so I deleted the branch and recreated one. That's why this pull request was closed. Please review the new pull request. Thank you :)