docs: add examples for facets
cmudig/draco2 pull request #235
Opened 2022-03-02 22:21 UTC by Zehua-Zeng

2022-03-03 01:45 UTC, domoritz requested changes
Make sure to run `make` before committing.

2022-03-03 01:45 UTC, domoritz commented on docs/facts/examples.ipynb
> +    "### Faceted Scatterplot on Horizontal Direction with Binning"
```suggestion
    "### Facet Scatterplot by Binned Data into Columns"
```

2022-03-03 01:45 UTC, domoritz commented on docs/facts/examples.ipynb
> +    "### Faceted Scatterplot on Horizontal Direction"
```suggestion
    "### Facet Scatterplot into Columns"
```

2022-03-03 19:36 UTC, Zehua-Zeng commented on docs/facts/examples.ipynb
> +   "execution_count": null,
Seems like running make doesnt help, need to run all examples manually

2022-03-05 16:42 UTC, domoritz requested changes
Please also add documentation and something in generate before we merge this.

2022-03-05 16:42 UTC, domoritz commented on docs/facts/examples.ipynb
> +      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
Fix this error

2022-03-08 22:00 UTC, domoritz approved these changes
Looks good. In a follow up pull request add constraints to restrict binning (and require it) for numeric fields.

2022-03-08 22:15 UTC, merged