refactor: add learn.py
cmudig/draco2 pull request #406
Opened 2022-09-29 03:27 UTC by JunranY

2022-09-29 03:38 UTC, JunranY commented
Added learn.py and data_utils that turns data pairs to training input. 
modified draco_learn notebook accordingly
fixed the math expression in doc

**Problem**: code coverage: I wasn't sure what test cases to write for draco-learn?

2022-10-05 15:03 UTC, domoritz requested changes
Remove

2022-10-05 15:03 UTC, domoritz commented on draco/data_utils.py
> +    """given specs, convert them into feature vectors."""
Make this a proper sentence

2022-10-05 15:03 UTC, domoritz commented on draco/data_utils.py
> +def get_nested_index(fields=None):
Can you add types?

2022-10-05 15:03 UTC, domoritz commented on draco/learn.py
> +    def train_and_plot(self, test_size: float = 0.3):
We should separate the training from the plotting. This way people can use only the training methods which is what most people will want. Moreover, we can then test only the training method. The plotting could either live in a notebook (I think that makes sense given that it's not polished yet) or I a separate method that we mark as not tested.

2022-10-05 15:03 UTC, domoritz commented on draco/learn.py
> +class DracoLearn:
I don't know whether this needs to be a class vs just a collection of methods. Is there benefit to having a class?

2022-10-07 16:04 UTC, domoritz approved these changes

2022-10-07 16:04 UTC, domoritz commented on draco/data_utils.py
> +    Given pairs of positive and negative draco specification, count the number of times
```suggestion
    Given pairs of positive and negative Draco specifications, count the number of times
```

2022-10-07 17:50 UTC, merged